import redis
r = redis.StrictRedis(host='localhost', port=6379, db=0)
r.flushdb()
r.rpush('mWT4The Godfather', 'Al Pacino')
r.rpush('mWT4The Godfather', 'Marlon Brando')
r.rpush('mWT4The Godfather', 'Robert Duvall')
r.rpush("mWT4Schindler's List", 'Liam Neeson')
r.rpush("mWT4Schindler's List", 'Ralph Fiennes')
r.rpush("mWT4Schindler's List", 'Ben Kingsley')
r.rpush('mWT4Saving Private', 'Ryan Tom Hanks')
r.rpush('mWT4Saving Private', 'Matt Damon')
r.rpush('mWT4Saving Private', 'Vin Diesel')
r.rpush('mWT4Back to the Future', 'Michael J. Fox')
r.rpush('mWT4Back to the Future', 'Christopher Lloyd')
r.rpush('mWT4Back to the Future', 'Lea Thompson')
r.rpush('mWT4Casablanca', 'Ingrid Bergman')
r.rpush('mWT4Casablanca', 'Humphrey Bogart')
r.rpush('mWT4Casablanca', 'Peter Lorre')
r.rpush('mWT4The Big Lebowski', 'Julianne Moore')
r.rpush('mWT4The Big Lebowski', 'Jeff Bridges')
r.rpush('mWT4The Big Lebowski', 'Tara Reid')