import redis
r = redis.StrictRedis(host='localhost', port=6379, db=0)
r.flushdb()
r.rpush('mThe Godfather', 'Al Pacino')
r.rpush('mThe Godfather', 'Marlon Brando')
r.rpush('mThe Godfather', 'Robert Duvall')
r.rpush("mSchindler's List", 'Liam Neeson')
r.rpush("mSchindler's List", 'Ralph Fiennes')
r.rpush("mSchindler's List", 'Ben Kingsley')
r.rpush('mSaving Private', 'Ryan Tom Hanks')
r.rpush('mSaving Private', 'Matt Damon')
r.rpush('mSaving Private', 'Vin Diesel')
r.rpush('mBack to the Future', 'Michael J. Fox')
r.rpush('mBack to the Future', 'Christopher Lloyd')
r.rpush('mBack to the Future', 'Lea Thompson')
r.rpush('mCasablanca', 'Ingrid Bergman')
r.rpush('mCasablanca', 'Humphrey Bogart')
r.rpush('mCasablanca', 'Peter Lorre')
r.rpush('mThe Big Lebowski', 'Julianne Moore')
r.rpush('mThe Big Lebowski', 'Jeff Bridges')
r.rpush('mThe Big Lebowski', 'Tara Reid')